"""Files Model Change

Revision ID: 1f2e12e7b5e3
Revises: 2635f4a35ce9
Create Date: 2025-04-07 09:37:29.456702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2e12e7b5e3'
down_revision = '2635f4a35ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('scan_type', sa.Enum('HealthCheck', 'FullScan', 'DirectScan', name='scantype'), nullable=False))
        batch_op.drop_column('scan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'scan', ['scan_id'], ['id'])
        batch_op.drop_column('scan_type')

    # ### end Alembic commands ###
