"""Enum Updated

Revision ID: 51e6be12e901
Revises: 1f2e12e7b5e3
Create Date: 2025-04-07 10:52:00.986521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e6be12e901'
down_revision = '1f2e12e7b5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('scan_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('QUICK', 'DIRECTORY', 'FULL', name='scantype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('scan_type',
               existing_type=sa.Enum('QUICK', 'DIRECTORY', 'FULL', name='scantype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
