"""Network Scanner Text Updated

Revision ID: 61577df8b0c2
Revises: d6a30b6ce347
Create Date: 2025-04-08 10:26:42.802284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '61577df8b0c2'
down_revision = 'd6a30b6ce347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_network', schema=None) as batch_op:
        batch_op.alter_column('network_scan_result',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_network', schema=None) as batch_op:
        batch_op.alter_column('network_scan_result',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
