"""Network Scanner File

Revision ID: d6a30b6ce347
Revises: be94e367c0b4
Create Date: 2025-04-08 10:24:43.063038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a30b6ce347'
down_revision = 'be94e367c0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network_scan_result', sa.JSON(), nullable=False),
    sa.Column('upload_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_network')
    # ### end Alembic commands ###
